[project]
name = "wsgr-speed-calculator"
version = "1.0.0"
description = "A command-line tool to calculate the mean speed of ships in the game `Warship Girls R`"
readme = ["README.md", "README_en.md"]
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.8.1",
    "pyinstaller>=6.13.0",
]
