name: Run tests and upload coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests and collect coverage
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: matrix.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
          if (Test-Path -Path '.\requirements.txt' -PathType Leaf) {pip install -r requirements.txt}

      - name: Test with unittest
        run: |
          python -m unittest

      - name: Generate coverage reports
        run: |
          uv run coverage run --parallel-mode -m unittest discover -s tests
          uv run coverage combine
          uv run coverage xml -i
        env:
          COVERAGE_RUN: True

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: syzomnia-el/WarshipGirlsR-Speed-Calculator
          files: ./coverage.xml